# Generated by Django 3.0 on 2019-12-07 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
