# Generated by Django 3.0 on 2019-12-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_auto_20191207_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='answer',
            field=models.CharField(default='', max_length=100),
        ),
    ]
